Spotify interface
labelekip/labelcode pull request #4
Opened 2023-11-13 15:44 UTC by BoBsmil3Y

Adding spotify interface to communicate with Spotify API

2023-11-13 21:18 UTC, tahina-netizen commented on src/main/java/org/labelapp/labelpackage/repository/SpotifyRepository.java
> +        return new ObjectMapper().readValue(response.body(), SpotifyCredentials.class);
J'ai essayé de lancer le code avec `mvn spring-boot:run` (j'ai bien défini la variable d'environnement `spotify_secret` au préalable), mais je crois que l'appel à `spotifyAuthorization()` échoue, comme le montre la capture ci-dessous :
![image](https://github.com/labelekip/labelcode/assets/67635152/f5c6231a-bff9-4f8a-b3d3-c02167dfb024)

Je pense que c'est parce que cette méthode ne gère pas le cas d'erreur, où la réponse de Spotify contient un champ "error". Peut-être qu'il vaut mieux gérer proprement ce cas d'erreur afin d'éviter que l'`ObjectMapper` ne se plante ?

2023-11-14 12:38 UTC, BoBsmil3Y commented on src/main/java/org/labelapp/labelpackage/entity/Album.java
> +    private String href;
Un lien pour ouvrir la musique sur Spotify. Selon la doc : A link to the Web API endpoint providing full details of the track

2023-11-14 12:55 UTC, thomas-delcroix requested changes

2023-11-14 13:04 UTC, BoBsmil3Y commented on src/main/java/org/labelapp/labelpackage/LabelpackageApplication.java
> +		SpotifyRepository spotifyRepository = new SpotifyRepository();
feur

2023-11-14 13:19 UTC, BoBsmil3Y commented
Changements effectués

2023-11-15 09:23 UTC, thomas-delcroix approved these changes

2023-11-15 09:23 UTC, merged

2023-11-16 15:28 UTC, tahina-netizen commented on src/main/java/org/labelapp/labelpackage/entity/Album.java
> +    private String href;
D'accord, merci !