Change repository to service to match convention
labelekip/labelcode pull request #5
Opened 2023-11-15 10:25 UTC by BoBsmil3Y

2023-11-15 10:48 UTC, thomas-delcroix commented
L'application ne démarre pas lors des tests parce que la clé API n'est pas défini dans l'environnement du système. On va devoir trouver un moyen de faire fonctionner tout ça ou mettre la clé API dans le fichier de conf

2023-11-16 22:58 UTC, thomas-delcroix requested changes

2023-11-16 22:58 UTC, thomas-delcroix commented on src/main/java/org/labelapp/labelpackage/service/impl/SpotifyServiceImpl.java
> +    public SpotifyServiceImpl() throws SecretKeyNotSetup {
Je vais être un peu chiant du coup mais je vais te proposer de modifier ton constructeur pour utiliser la beauté de Spring. On va injecter en argument la valeur associée à 'spotify.apikey' définie dans la config : 

```java
public SpotifyServiceImpl(@Value("${spotify.apikey}") String secret) throws SecretKeyNotSetup {
        if (secret == null)
            throw new SecretKeyNotSetup();
        this.clientSecret = secret;
    }
```

Il faudra alors modifier le fichier `application.properties` pour mettre ce champ : 
```
spotify.apikey=${spotify_secret}
```

`${spotify_secret}` va tout simplement récupérer la valeur associée à 'spotify_secret' dans les variables d'environnement.

2023-11-21 13:03 UTC, BoBsmil3Y commented
C'est ok là non ?

2023-11-21 13:11 UTC, thomas-delcroix approved these changes

2023-11-21 13:12 UTC, merged